<?php

/**
 * Default value for variables that should be replaced.
 * Do not edit this value, since it is used in other classes to check the respective module is
 * configured or not.
 */
const TO_BE_REPLACED = '<TO BE REPLACED>';

// BEGIN OF VARIABLES THAT SHOULD BE EDITED
/**
 * Name of the cluster
 */
const CLUSTER_NAME = TO_BE_REPLACED;
/**
 * Name of the admin. Publicly available in error messages.
 */
const ADMIN_NAMES = TO_BE_REPLACED;
/**
 * E-Mail address of the admin. Publicly available in error messages.
 */
const ADMIN_EMAIL = TO_BE_REPLACED;
/**
 * Hostname of the login node.
 */
const SLURM_LOGIN_NODE = TO_BE_REPLACED;
/**
 * Link to a wiki page where one can find more info about the cluster.
 */
const WIKI_LINK = TO_BE_REPLACED;

// Rest API connection properties
/**
 * Connection more for connections to slurmrestd.
 * Currently, the only supported value is 'unix'!
 */
const CONNECTION_MODE = 'unix';
/**
 * OpenAPI version to use for communication with slurmrestd.
 * Use 'auto' for auto-detection (if supported), or e.g. v0.0.40.
 * Default is 'auto'.
 */
const REST_API_VERSION = 'auto';

// LDAP configuration
/**
 * URI for ldap server, e.g. 'dc.example.com'
 * Optional; leave TO_BE_REPLACED if you do not want to use authentication method LDAP.
 */
const LDAP_URI = TO_BE_REPLACED;
/**
 * LDAP base, e.g. 'cn=users,dc=i,dc=example,dc=com'
 * Optional; leave TO_BE_REPLACED if you do not want to use authentication method LDAP.
 */
const LDAP_BASE = TO_BE_REPLACED;
/**
 * LDAP admin user to query for the users, e.g. 'adminuser'
 * Optional; leave TO_BE_REPLACED if you do not want to use authentication method LDAP.
 */
const LDAP_ADMIN_USER = TO_BE_REPLACED;
/**
 * Password for the LDAP admin user.
 * Optional; leave TO_BE_REPLACED if you do not want to use authentication method LDAP.
 */
const LDAP_ADMIN_PASSWORD = TO_BE_REPLACED;

// SSH configuration for local authentication
/**
 * Url that is used to connect via SSH to. Can be e.g. the login node.
 * Example: slurm01.example.com
 * Optional; leave TO_BE_REPLACED if you do not want to use authentication method local.
 */
const SSH_SERVER_URL = TO_BE_REPLACED;

// JWT configuration
/**
 * Path to the JWT key.
 * Optional; leave TO_BE_REPLACED if you do not want to use JWT authentication.
 */
const JWT_PATH = TO_BE_REPLACED;


/**
 * Grant some users read access to e.g. the list of SLURM users.
 * Admins always have access.
 */
$privileged_users = array();

// END OF VARIABLES THAT SHOULD BE EDITED
//
// DO NOT EDIT THIS FILE FROM HERE ON!

// Global error handling
if(!isset($errormsg)){
    $errormsg = "";
}
$successmsg = "";

/**
 * Add an error that will be displayed on the page later.
 * @param $s string Error message
 */
function addError(string $s): void {
    global $errormsg;
    global $error;
    $error = TRUE;

    #$user = isset($_SESSION['USER']) ? $_SESSION['USER'] : "-";
    #$ip = $_SERVER['REMOTE_ADDR'];
    #$host = $_SERVER['HTTP_HOST'] ?? '-';

    $errormsg .= '<li>' . $s . '</li>';
}

/**
 * Add a success message that will be displayed on the website later.
 * @param $s string Success message
 */
function addSuccess(string $s): void {
    global $successmsg;

    $successmsg .= '<li>' . $s . '</li>';
}


function internalServerError(Throwable $exception) : void {
    $debug_info='';
    if(is_callable([$exception, 'get_debug_info']))
        $debug_info = $exception->get_debug_info();

    error_log(
        "slurm-dashboard: Uncaught Exception: " . $exception->getMessage() .
        "; at " . $exception->getFile() . ":" . $exception->getLine() . " with code " .
        $exception->getCode() . "; Trace:" . $exception->getTraceAsString() .
        "; Debug info: " . $debug_info
    );

    while (ob_get_level()) {
        ob_end_clean();
    }
    http_response_code(500);
    include __DIR__ . '/error.php';
}

set_exception_handler('internalServerError');
set_error_handler(function($errno, $errstr, $errfile, $errline) {
    throw new ErrorException($errstr, 0, $errno, $errfile, $errline);
});