<?php

/**
 * Default value for variables that should be replaced.
 * Do not edit this value, since it is used in other classes to check the respective module is
 * configured or not.
 */
const TO_BE_REPLACED = '<TO BE REPLACED>';
/**
 * Helper to read environment vars with fallback.
 */
function cfg_env(string $name, string $default = TO_BE_REPLACED) : string {
    $value = getenv($name);
    return ($value !== FALSE && $value !== '') ? $value : $default;
}

/**
 * Main configuration array.
 * You can override the values here, but it is recommended to set them as environment variables.
 */
$config = [

    /**
     * Name of the cluster.
     */
    'CLUSTER_NAME' => cfg_env('CLUSTER_NAME'),

    /**
     * Name of the admin. Publicly available in error messages.
     */
    'ADMIN_NAMES' => cfg_env('ADMIN_NAMES'),

    /**
     * E-Mail address of the admin. Publicly available in error messages.
     */
    'ADMIN_EMAIL' => cfg_env('ADMIN_EMAIL'),

    /**
     * Hostname of the login node.
     */
    'SLURM_LOGIN_NODE' => cfg_env('SLURM_LOGIN_NODE'),

    /**
     * Link to a wiki page where one can find more info about the cluster.
     */
    'WIKI_LINK' => cfg_env('WIKI_LINK'),

    // ------------------------------------------------------------------
    // REST API CONNECTION PROPERTIES
    // ------------------------------------------------------------------

    /**
     * Connection mode for connections to slurmrestd.
     * Currently, the only supported value is 'unix'!
     */
    'CONNECTION_MODE' => cfg_env('CONNECTION_MODE', 'unix'),

    /**
     * OpenAPI version to use for communication with slurmrestd.
     * Use 'auto' for auto-detection (if supported), or e.g. v0.0.40.
     * Default is 'auto'.
     */
    'REST_API_VERSION' => cfg_env('REST_API_VERSION', 'auto'),

    // ------------------------------------------------------------------
    // LDAP CONFIGURATION
    // ------------------------------------------------------------------

    /**
     * URI for LDAP server, e.g. 'dc.example.com'.
     * Optional; leave TO_BE_REPLACED if you do not want to use LDAP authentication.
     */
    'LDAP_URI' => cfg_env('LDAP_URI'),

    /**
     * LDAP base, e.g. 'cn=users,dc=i,dc=example,dc=com'.
     * Optional; leave TO_BE_REPLACED if you do not want to use LDAP authentication.
     */
    'LDAP_BASE' => cfg_env('LDAP_BASE'),

    /**
     * LDAP admin user used for querying users, e.g. 'adminuser'.
     * Optional; leave TO_BE_REPLACED if you do not want to use LDAP authentication.
     */
    'LDAP_ADMIN_USER' => cfg_env('LDAP_ADMIN_USER'),

    /**
     * Password for the LDAP admin user.
     * Optional; leave TO_BE_REPLACED if you do not want to use LDAP authentication.
     */
    'LDAP_ADMIN_PASSWORD' => cfg_env('LDAP_ADMIN_PASSWORD'),

    // ------------------------------------------------------------------
    // SSH CONFIGURATION (LOCAL AUTHENTICATION)
    // ------------------------------------------------------------------

    /**
     * URL used for SSH connections, e.g. the login node.
     * Example: slurm01.example.com.
     * Optional; leave TO_BE_REPLACED if you do not want to use local authentication.
     */
    'SSH_SERVER_URL' => cfg_env('SSH_SERVER_URL'),

    // ------------------------------------------------------------------
    // JWT CONFIGURATION
    // ------------------------------------------------------------------

    /**
     * Path to the JWT key.
     * Optional; leave TO_BE_REPLACED if you do not want to use JWT authentication.
     */
    'JWT_PATH' => cfg_env('JWT_PATH'),

    // ------------------------------------------------------------------
    // MISC
    // ------------------------------------------------------------------

    /**
     * Username of the Slurm user.
     * Defaults to 'slurm'.
     */
    'SLURM_USER' => cfg_env('SLURM_USER', 'slurm'),

    'PRIV_USERS' => explode(',', getenv('PRIV_USERS') ?: '')
];

function config($key = null) {
    global $config;
    return $key ? $config[$key] : $config;
}

// END OF VARIABLES THAT SHOULD BE EDITED
//
// DO NOT EDIT THIS FILE FROM HERE ON!

// Global error handling
if(!isset($errormsg)){
    $errormsg = "";
}
$successmsg = "";

/**
 * Add an error that will be displayed on the page later.
 * @param $s string Error message
 */
function addError(string $s): void {
    global $errormsg;
    global $error;
    $error = TRUE;

    $errormsg .= '<li>' . $s . '</li>';
}

/**
 * Add a success message that will be displayed on the website later.
 * @param $s string Success message
 */
function addSuccess(string $s): void {
    global $successmsg;

    $successmsg .= '<li>' . $s . '</li>';
}


function internalServerError(Throwable $exception) : void {
    $debug_info='';
    if(is_callable([$exception, 'get_debug_info']))
        $debug_info = $exception->get_debug_info();

    error_log(
        "slurm-dashboard: Uncaught Exception: " . $exception->getMessage() .
        "; at " . $exception->getFile() . ":" . $exception->getLine() . " with code " .
        $exception->getCode() . "; Trace:" . $exception->getTraceAsString() .
        "; Debug info: " . $debug_info
    );

    while (ob_get_level()) {
        ob_end_clean();
    }
    http_response_code(500);
    include __DIR__ . '/error.php';
}

set_exception_handler('internalServerError');
set_error_handler(function($errno, $errstr, $errfile, $errline) {
    throw new ErrorException($errstr, 0, $errno, $errfile, $errline);
});